<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <TITLE>Przyklad POST</TITLE>
</HEAD>

<H1 ALIGN="CENTER">Przyklad HTTP POST</H1>

<FORM ACTION="http://localhost:8080/book-search"
      METHOD="POST">
  Parametr 1:
  <INPUT TYPE="TEXT" NAME="parametr1"><BR>
  Parametr 2:
  <INPUT TYPE="TEXT" NAME="parametr2"><BR>
  Parametr 3:
  <INPUT TYPE="TEXT" NAME="parametr3"><BR>
  <INPUT TYPE="SUBMIT" VALUE="Wyslij">
</FORM>

</BODY>
</HTML>